name: mealprep
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.9
  webview_flutter: ^3.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "dev_assets/logo-circles.png"
  adaptive_icon_background: "#262B37"
  adaptive_icon_foreground: "dev_assets/logo-circles.png"


  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true


  assets:
    - assets/images/

 
  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          style: normal
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 600
 
